set_location_assignment PIN_K10 -to IO_DIFFIO_B18p
set_location_assignment PIN_K9 -to IO_DIFFIO_B13p
set_location_assignment PIN_L10 -to IO_DIFFIO_B18n
set_location_assignment PIN_L11 -to IO_DIFFIO_B21n
set_location_assignment PIN_L9 -to IO_DIFFIO_B13n
set_location_assignment PIN_M10 -to IO_RUP2
set_location_assignment PIN_M11 -to IO_DIFFIO_B22p
set_location_assignment PIN_M9 -to IO_DIFFIO_B14p
set_location_assignment PIN_N11 -to IO_RDN2
set_location_assignment PIN_N12 -to IO_DIFFIO_B22n
set_location_assignment PIN_N9 -to IO_DIFFIO_B14n
set_location_assignment PIN_P11 -to IO_VREFB4N0
set_location_assignment PIN_P14 -to IO_DIFFIO_B21p
set_location_assignment PIN_P9 -to IO_P9
set_location_assignment PIN_R10 -to IO_DIFFIO_B15p
set_location_assignment PIN_R11 -to IO_DIFFIO_B16p
set_location_assignment PIN_R12 -to IO_DIFFIO_B17p
set_location_assignment PIN_R13 -to IO_DIFFIO_B19p
set_location_assignment PIN_R14 -to IO_R14
set_location_assignment PIN_R9 -to IO_DIFFIO_B12p
set_location_assignment PIN_T10 -to IO_DIFFIO_B15n
set_location_assignment PIN_T11 -to IO_DIFFIO_B16n
set_location_assignment PIN_T12 -to IO_DIFFIO_B17n
set_location_assignment PIN_T13 -to IO_DIFFIO_B19n
set_location_assignment PIN_T14 -to IO_DIFFIO_B20p
set_location_assignment PIN_T15 -to IO_DIFFIO_B20n_DPCLK3
set_location_assignment PIN_T9 -to IO_DIFFIO_B12n
set_location_assignment PIN_A2 -to IO_DIFFIO_T5n
set_location_assignment PIN_A3 -to IO_DIFFIO_T2n
set_location_assignment PIN_A4 -to IO_DIFFIO_T4n
set_location_assignment PIN_A5 -to IO_DATA7
set_location_assignment PIN_A6 -to IO_DIFFIO_T7n
set_location_assignment PIN_A7 -to IO_DIFFIO_T9n
set_location_assignment PIN_A8 -to IO_DIFFIO_T11n
set_location_assignment PIN_B3 -to IO_DIFFIO_T2p_DPCLK7
set_location_assignment PIN_B4 -to IO_DIFFIO_T4p
set_location_assignment PIN_B5 -to IO_DIFFIO_T5p
set_location_assignment PIN_B6 -to IO_DIFFIO_T7p
set_location_assignment PIN_B7 -to IO_DIFFIO_T9p_DATA4
set_location_assignment PIN_B8 -to IO_DIFFIO_T11p
set_location_assignment PIN_C3 -to IO_DIFFIO_T1n
set_location_assignment PIN_C6 -to IO_VREFB8N0
set_location_assignment PIN_C8 -to IO_C8
set_location_assignment PIN_D3 -to IO_DIFFIO_T1p
set_location_assignment PIN_D5 -to IO_DIFFIO_T3n
set_location_assignment PIN_D6 -to IO_DIFFIO_T3p
set_location_assignment PIN_D8 -to IO_D8
set_location_assignment PIN_E6 -to IO_DATA6
set_location_assignment PIN_E7 -to IO_DATA5
set_location_assignment PIN_E8 -to IO_DIFFIO_T10n_DATA2
set_location_assignment PIN_F6 -to IO_DIFFIO_T8n
set_location_assignment PIN_F7 -to IO_DIFFIO_T8p
set_location_assignment PIN_F8 -to IO_DIFFIO_T10p_DATA3
set_location_assignment PIN_B1 -to IO_B1
set_location_assignment PIN_C1 -to IO_DIFFIO_L1n_DATA1_ASDO
set_location_assignment PIN_C2 -to IO_DIFFIO_L1p
set_location_assignment PIN_D1 -to IO_DIFFIO_L2n
set_location_assignment PIN_D2 -to IO_DIFFIO_L2p_FLASH_nCE_nCSO
set_location_assignment PIN_D4 -to IO_D4
set_location_assignment PIN_E1 -to CLK1
set_location_assignment PIN_E5 -to IO_E5
set_location_assignment PIN_F1 -to IO_DIFFIO_L3n
set_location_assignment PIN_F2 -to IO_DIFFIO_L3p
set_location_assignment PIN_F3 -to IO_VREFB1N0
set_location_assignment PIN_F4 -to nSTATUS
set_location_assignment PIN_F5 -to IO_F5
set_location_assignment PIN_G1 -to IO_DIFFIO_L4n
set_location_assignment PIN_G2 -to IO_DIFFIO_L4p_DPCLK0
set_location_assignment PIN_G5 -to IO_G5
set_location_assignment PIN_H1 -to DCLK
set_location_assignment PIN_H2 -to IO_DATA0
set_location_assignment PIN_H3 -to TCK
set_location_assignment PIN_H4 -to TDI
set_location_assignment PIN_H5 -to nCONFIG
set_location_assignment PIN_J3 -to nCE
set_location_assignment PIN_J4 -to TDO
set_location_assignment PIN_J5 -to TMS
set_location_assignment PIN_J11 -to IO_J11
set_location_assignment PIN_J12 -to IO_DIFFIO_R6p
set_location_assignment PIN_J13 -to IO_J13
set_location_assignment PIN_J14 -to IO_DIFFIO_R6n
set_location_assignment PIN_J15 -to IO_DIFFIO_R7p_DEV_CLRn
set_location_assignment PIN_J16 -to IO_DIFFIO_R7n_DEV_OE
set_location_assignment PIN_K11 -to IO_K11
set_location_assignment PIN_K12 -to IO_K12
set_location_assignment PIN_K15 -to IO_DIFFIO_R8p_DPCLK4
set_location_assignment PIN_K16 -to IO_DIFFIO_R8n
set_location_assignment PIN_L12 -to IO_L12
set_location_assignment PIN_L13 -to IO_L13
set_location_assignment PIN_L14 -to IO_VREFB5N0
set_location_assignment PIN_L15 -to IO_DIFFIO_R9p
set_location_assignment PIN_L16 -to IO_DIFFIO_R9n
set_location_assignment PIN_M12 -to IO_M12
set_location_assignment PIN_M15 -to CLK6
set_location_assignment PIN_M16 -to CLK7
set_location_assignment PIN_N13 -to IO_N13
set_location_assignment PIN_N14 -to IO_RUP3
set_location_assignment PIN_N15 -to IO_DIFFIO_R10p
set_location_assignment PIN_N16 -to IO_DIFFIO_R10n
set_location_assignment PIN_P15 -to IO_RDN3
set_location_assignment PIN_P16 -to IO_DIFFIO_R11n
set_location_assignment PIN_R16 -to IO_DIFFIO_R11p
set_location_assignment PIN_J1 -to IO_DIFFIO_L5n
set_location_assignment PIN_J2 -to IO_DIFFIO_L5p
set_location_assignment PIN_J6 -to IO_J6
set_location_assignment PIN_K1 -to IO_DIFFIO_L7n
set_location_assignment PIN_K2 -to IO_DIFFIO_L7p
set_location_assignment PIN_K5 -to IO_RUP1
set_location_assignment PIN_K6 -to IO_DIFFIO_L6p
set_location_assignment PIN_L1 -to IO_DIFFIO_L8n
set_location_assignment PIN_L2 -to IO_DIFFIO_L8p_DPCLK1
set_location_assignment PIN_L3 -to IO_VREFB2N0
set_location_assignment PIN_L4 -to IO_RDN1
set_location_assignment PIN_L6 -to IO_DIFFIO_L6n
set_location_assignment PIN_M1 -to CLK3
set_location_assignment PIN_M2 -to CLK2
set_location_assignment PIN_N1 -to IO_DIFFIO_L9n
set_location_assignment PIN_N2 -to IO_DIFFIO_L9p
set_location_assignment PIN_P1 -to IO_DIFFIO_L10n
set_location_assignment PIN_P2 -to IO_DIFFIO_L10p
set_location_assignment PIN_R1 -to IO_R1
set_location_assignment PIN_B16 -to IO_DPCLK5
set_location_assignment PIN_C15 -to IO_DIFFIO_R1p
set_location_assignment PIN_C16 -to IO_DIFFIO_R1n
set_location_assignment PIN_D15 -to IO_DIFFIO_R2p
set_location_assignment PIN_D16 -to IO_DIFFIO_R2n
set_location_assignment PIN_E15 -to CLK4
set_location_assignment PIN_E16 -to CLK5
set_location_assignment PIN_F13 -to IO_F13
set_location_assignment PIN_F14 -to IO_VREFB6N0
set_location_assignment PIN_F15 -to IO_DIFFIO_R3p_CLKUSR
set_location_assignment PIN_F16 -to IO_DIFFIO_R3n_nCEO
set_location_assignment PIN_G11 -to IO_G11
set_location_assignment PIN_G12 -to MSEL2
set_location_assignment PIN_G15 -to IO_DIFFIO_R4p_CRC_ERROR
set_location_assignment PIN_G16 -to IO_DIFFIO_R4n_INIT_DONE
set_location_assignment PIN_H12 -to MSEL1
set_location_assignment PIN_H13 -to MSEL0
set_location_assignment PIN_H14 -to CONF_DONE
set_location_assignment PIN_K8 -to IO_DIFFIO_B5n
set_location_assignment PIN_L7 -to IO_L7
set_location_assignment PIN_L8 -to IO_DIFFIO_B9p
set_location_assignment PIN_M6 -to IO_M6
set_location_assignment PIN_M7 -to IO_DIFFIO_B5p
set_location_assignment PIN_M8 -to IO_DIFFIO_B9n
set_location_assignment PIN_N3 -to IO_DIFFIO_B1p
set_location_assignment PIN_N5 -to IO_DIFFIO_B4p
set_location_assignment PIN_N6 -to IO_DIFFIO_B4n
set_location_assignment PIN_N8 -to IO_DIFFIO_B10p
set_location_assignment PIN_P3 -to IO_DIFFIO_B1n
set_location_assignment PIN_P6 -to IO_VREFB3N0
set_location_assignment PIN_P8 -to IO_DIFFIO_B10n
set_location_assignment PIN_R3 -to IO_DIFFIO_B2p
set_location_assignment PIN_R4 -to IO_PLL1_CLKOUTp
set_location_assignment PIN_R5 -to IO_DIFFIO_B6p
set_location_assignment PIN_R6 -to IO_DIFFIO_B7p
set_location_assignment PIN_R7 -to IO_DIFFIO_B8p
set_location_assignment PIN_R8 -to IO_DIFFIO_B11p
set_location_assignment PIN_T2 -to IO_DPCLK2
set_location_assignment PIN_T3 -to IO_DIFFIO_B2n
set_location_assignment PIN_T4 -to IO_PLL1_CLKOUTn
set_location_assignment PIN_T5 -to IO_DIFFIO_B6n
set_location_assignment PIN_T6 -to IO_DIFFIO_B7n
set_location_assignment PIN_T7 -to IO_DIFFIO_B8n
set_location_assignment PIN_T8 -to IO_DIFFIO_B11n
set_location_assignment PIN_A10 -to IO_DIFFIO_T14n
set_location_assignment PIN_A11 -to IO_DIFFIO_T17n
set_location_assignment PIN_A12 -to IO_DIFFIO_T18n
set_location_assignment PIN_A13 -to IO_DIFFIO_T19n
set_location_assignment PIN_A14 -to IO_PLL2_CLKOUTn
set_location_assignment PIN_A15 -to IO_DIFFIO_T15p
set_location_assignment PIN_A9 -to IO_DIFFIO_T12n
set_location_assignment PIN_B10 -to IO_DIFFIO_T14p
set_location_assignment PIN_B11 -to IO_DIFFIO_T17p
set_location_assignment PIN_B12 -to IO_DIFFIO_T18p
set_location_assignment PIN_B13 -to IO_DIFFIO_T19p
set_location_assignment PIN_B14 -to IO_PLL2_CLKOUTp
set_location_assignment PIN_B9 -to IO_DIFFIO_T12p
set_location_assignment PIN_C11 -to IO_VREFB7N0
set_location_assignment PIN_C14 -to IO_DIFFIO_T21n
set_location_assignment PIN_C9 -to IO_DIFFIO_T13n
set_location_assignment PIN_D11 -to IO_DIFFIO_T20n
set_location_assignment PIN_D12 -to IO_DIFFIO_T20p_DPCLK6
set_location_assignment PIN_D14 -to IO_DIFFIO_T21p
set_location_assignment PIN_D9 -to IO_DIFFIO_T13p
set_location_assignment PIN_E10 -to IO_RDN4
set_location_assignment PIN_E11 -to IO_RUP4
set_location_assignment PIN_E9 -to IO_E9
set_location_assignment PIN_F10 -to IO_DIFFIO_T16n
set_location_assignment PIN_F11 -to IO_DIFFIO_T15n
set_location_assignment PIN_F9 -to IO_DIFFIO_T16p
